function out1 = f_peak(x,y)
%F_PEAK
%    OUT1 = F_PEAK(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    19-Mar-2023 22:18:43

t2 = x.^2;
t3 = y.^2;
t4 = -t2;
t5 = -t3;
out1 = exp(t5-(x+1.0).^2).*(-1.0./3.0)+exp(t4-(y+1.0).^2).*(x-1.0).^2.*3.0+exp(t4+t5).*(x.*-2.0+x.^3.*1.0e+1+y.^5.*1.0e+1);
