function out1 = g_peak(x,y)
%G_PEAK
%    OUT1 = G_PEAK(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    19-Mar-2023 22:18:43

t2 = x.*2.0;
t3 = x+1.0;
t4 = x.^2;
t5 = x.^3;
t6 = y+1.0;
t7 = y.^2;
t8 = y.^5;
t10 = x-1.0;
t9 = -t2;
t11 = t3.^2;
t12 = t6.^2;
t13 = -t4;
t14 = t5.*1.0e+1;
t15 = t10.^2;
t16 = -t7;
t17 = t8.*1.0e+1;
t18 = -t11;
t19 = -t12;
t20 = t13+t16;
t26 = t9+t14+t17;
t21 = exp(t20);
t22 = t16+t18;
t23 = t13+t19;
t24 = exp(t22);
t25 = exp(t23);
out1 = [t21.*(t4.*3.0e+1-2.0)+(t24.*(t2+2.0))./3.0+t25.*(t2-2.0).*3.0-t15.*t25.*x.*6.0-t21.*t26.*x.*2.0;t24.*y.*(2.0./3.0)+t7.^2.*t21.*5.0e+1-t6.*t15.*t25.*6.0-t21.*t26.*y.*2.0];
