function out1 = g_square(x,y)
%G_SQUARE
%    OUT1 = G_SQUARE(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    19-Mar-2023 22:18:43

out1 = [x.*2.0;y.*2.0];
